# docs/_config.yml
title: Documentation Automation
description: Automate the deployment of your documentation to GitHub Pages using GitHub Actions.
theme: just-the-docs

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs

# Set the base URL to match your GitHub Pages URL
baseurl: "/documentation-automation"  # Replace with your repository name
url: "https://SingularityNET-Archive.github.io"

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "https://github.com/SingularityNET-Archive/documentation-automation"

# Color scheme
color_scheme: dark

# Enable collect for search functionality
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10